// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price_service.proto

package protos;

public interface CountryPriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CountryPrice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country = 1;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 1;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>int32 price1S = 2;</code>
   */
  int getPrice1S();

  /**
   * <code>int32 price2S = 3;</code>
   */
  int getPrice2S();

  /**
   * <code>int32 price4S = 4;</code>
   */
  int getPrice4S();

  /**
   * <code>string currency = 5;</code>
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 5;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();
}
