// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price_service.proto

package protos;

public interface CountryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CountryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country = 1;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 1;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();
}
