// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price_service.proto

package protos;

public interface CustomerPriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomerPrice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 price = 1;</code>
   */
  int getPrice();
}
