// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price_service.proto

package protos;

public interface CustomerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string country = 2;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 2;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string plan = 3;</code>
   */
  java.lang.String getPlan();
  /**
   * <code>string plan = 3;</code>
   */
  com.google.protobuf.ByteString
      getPlanBytes();
}
