// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price_service.proto

package protos;

public interface CustomerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
