// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price_service.proto

package protos;

public final class PriceGuideProtos {
  private PriceGuideProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerPrice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerPrice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomerInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllCountryPrice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllCountryPrice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CountryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CountryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CountryPrice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CountryPrice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023price_service.proto\"\035\n\017CustomerRequest" +
      "\022\n\n\002id\030\001 \001(\t\"\036\n\rCustomerPrice\022\r\n\005price\030\001" +
      " \001(\005\"9\n\014CustomerInfo\022\n\n\002id\030\001 \001(\t\022\017\n\007coun" +
      "try\030\002 \001(\t\022\014\n\004plan\030\003 \001(\t\"6\n\017AllCountryPri" +
      "ce\022#\n\014countryPrice\030\001 \003(\0132\r.CountryPrice\"" +
      "K\n\006Status\022 \n\004stat\030\001 \001(\0162\022.Status.StatusT" +
      "ype\"\037\n\nStatusType\022\006\n\002OK\020\000\022\t\n\005ERROR\020\001\"!\n\016" +
      "CountryRequest\022\017\n\007country\030\001 \001(\t\"d\n\014Count" +
      "ryPrice\022\017\n\007country\030\001 \001(\t\022\017\n\007price1S\030\002 \001(" +
      "\005\022\017\n\007price2S\030\003 \001(\005\022\017\n\007price4S\030\004 \001(\005\022\020\n\010c",
      "urrency\030\005 \001(\t2\262\001\n\nPriceGuide\0221\n\022updateGl" +
      "obalPrices\022\020.AllCountryPrice\032\007.Status\"\000\022" +
      "6\n\022getPriceForCountry\022\017.CountryRequest\032\r" +
      ".CountryPrice\"\000\0229\n\023getPriceForCustomer\022\020" +
      ".CustomerRequest\032\016.CustomerPrice\"\000B\034\n\006pr" +
      "otosB\020PriceGuideProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_CustomerPrice_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CustomerPrice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerPrice_descriptor,
        new java.lang.String[] { "Price", });
    internal_static_CustomerInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CustomerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomerInfo_descriptor,
        new java.lang.String[] { "Id", "Country", "Plan", });
    internal_static_AllCountryPrice_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AllCountryPrice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllCountryPrice_descriptor,
        new java.lang.String[] { "CountryPrice", });
    internal_static_Status_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Status_descriptor,
        new java.lang.String[] { "Stat", });
    internal_static_CountryRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CountryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CountryRequest_descriptor,
        new java.lang.String[] { "Country", });
    internal_static_CountryPrice_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_CountryPrice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CountryPrice_descriptor,
        new java.lang.String[] { "Country", "Price1S", "Price2S", "Price4S", "Currency", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
