// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price_service.proto

package protos;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Status.StatusType stat = 1;</code>
   */
  int getStatValue();
  /**
   * <code>.Status.StatusType stat = 1;</code>
   */
  protos.Status.StatusType getStat();
}
